export const products = [
    {
        name: 'Vanguard Chronograph',
        slug: 'vanguard-chronograph',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1000',
        brand: 'Aethelgard',
        category: 'Timepieces',
        description: 'A masterpiece of engineering and design. The Vanguard Chronograph features a surgical-grade steel case, sapphire crystal, and an automatic movement with 72-hour power reserve.',
        price: 2450.00,
        countInStock: 5,
        rating: 4.8,
        numReviews: 12,
    },
    {
        name: 'Nordic Minimalist Desk',
        slug: 'nordic-minimalist-desk',
        image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=1000',
        brand: 'Lume',
        category: 'Interior',
        description: 'Crafted from sustainable solid ash, this desk combines clean lines with functional elegance. Features an integrated cable management system and a tactile, soft-touch finish.',
        price: 890.00,
        countInStock: 8,
        rating: 4.9,
        numReviews: 8,
    },
    {
        name: 'Aura Wireless Headphones',
        slug: 'aura-wireless-headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000',
        brand: 'SonicStream',
        category: 'Electronics',
        description: 'Immersive sound meets effortless style. The Aura features adaptive active noise cancellation, spatial audio support, and 40 hours of battery life on a single charge.',
        price: 349.00,
        countInStock: 15,
        rating: 4.7,
        numReviews: 24,
    },
    {
        name: 'Elysian Leather Briefcase',
        slug: 'elysian-leather-briefcase',
        image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=1000',
        brand: 'Heritage',
        category: 'Accessories',
        description: 'The ultimate companion for the modern professional. Handmade from full-grain vegetable-tanned leather that develops a beautiful patina over time.',
        price: 520.00,
        countInStock: 10,
        rating: 4.9,
        numReviews: 15,
    },
    {
        name: 'Zenith Smart Light',
        slug: 'zenith-smart-light',
        image: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&q=80&w=1000',
        brand: 'Lume',
        category: 'Electronics',
        description: 'Transform your space with the Zenith Smart Light. Adjustable color temperature, app control, and a sleek, minimalist design that fits any modern interior.',
        price: 189.00,
        countInStock: 20,
        rating: 4.5,
        numReviews: 30,
    },
    {
        name: 'Oasis Ceramic Planter',
        slug: 'oasis-ceramic-planter',
        image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&q=80&w=1000',
        brand: 'Terra',
        category: 'Interior',
        description: 'A touch of nature for your sanctuary. This hand-thrown ceramic planter features a unique reactive glaze finish, making every piece one-of-a-kind.',
        price: 75.00,
        countInStock: 25,
        rating: 4.6,
        numReviews: 18,
    }
];

export const users = [
    {
        name: 'Admin User',
        email: 'admin@example.com',
        password: 'password123',
        isAdmin: true,
    },
    {
        name: 'John Doe',
        email: 'john@example.com',
        password: 'password123',
    },
    {
        name: 'Jane Smith',
        email: 'jane@example.com',
        password: 'password123',
    }
];
